"""Seed data for quiz-derived vocabulary cards.

These cards are intentionally concise: one short Chinese gloss plus one very
simple Japanese example sentence. The source song / URL is attached later from
the linked quiz question rows.
"""

from __future__ import annotations

QUIZ_VOCAB_SEED: dict[str, dict[str, str]] = {
    "いがみ合って": {"reading_hiragana": "いがみあって", "zh_gloss_short": "互相爭執", "example_ja": "二人はいがみ合っていた。"},
    "ぞんざいな": {"reading_hiragana": "ぞんざいな", "zh_gloss_short": "草率、隨便", "example_ja": "ぞんざいな返事はよくない。"},
    "たられば": {"reading_hiragana": "たられば", "zh_gloss_short": "如果當初就…", "example_ja": "たらればを言っても仕方ない。"},
    "どうだっていいや": {"reading_hiragana": "どうだっていいや", "zh_gloss_short": "怎樣都無所謂", "example_ja": "もうどうだっていいやと思った。"},
    "ぽっかり": {"reading_hiragana": "ぽっかり", "zh_gloss_short": "空空地、突然地", "example_ja": "雲の間に穴がぽっかり空いた。"},
    "みっともない": {"reading_hiragana": "みっともない", "zh_gloss_short": "難看、不體面", "example_ja": "みっともない言い訳はやめよう。"},
    "わざとらしい": {"reading_hiragana": "わざとらしい", "zh_gloss_short": "做作、不自然", "example_ja": "その笑い方はわざとらしい。"},
    "わめき散らす": {"reading_hiragana": "わめきちらす", "zh_gloss_short": "大吵大鬧", "example_ja": "彼は夜中にわめき散らした。"},
    "一筋縄ではいかない": {"reading_hiragana": "ひとすじなわではいかない", "zh_gloss_short": "不容易對付", "example_ja": "その相手は一筋縄ではいかない。"},
    "一蓮托生": {"reading_hiragana": "いちれんたくしょう", "zh_gloss_short": "同生共死", "example_ja": "私たちは一蓮托生だ。"},
    "不器用": {"reading_hiragana": "ぶきよう", "zh_gloss_short": "笨拙、不靈巧", "example_ja": "彼は不器用だが優しい。"},
    "二面性": {"reading_hiragana": "にめんせい", "zh_gloss_short": "兩面性", "example_ja": "人には二面性がある。"},
    "仄暗い": {"reading_hiragana": "ほのぐらい", "zh_gloss_short": "微暗、陰沉的", "example_ja": "仄暗い部屋で一人で考えた。"},
    "伽藍堂": {"reading_hiragana": "がらんどう", "zh_gloss_short": "空空如也", "example_ja": "会場は伽藍堂になった。"},
    "倦怠": {"reading_hiragana": "けんたい", "zh_gloss_short": "倦怠、疲乏", "example_ja": "午後は強い倦怠を感じた。"},
    "催涙": {"reading_hiragana": "さいるい", "zh_gloss_short": "催淚", "example_ja": "その映画は催涙ものだ。"},
    "傲慢": {"reading_hiragana": "ごうまん", "zh_gloss_short": "傲慢", "example_ja": "傲慢な態度は嫌われる。"},
    "八百万": {"reading_hiragana": "やおよろず", "zh_gloss_short": "數量極多", "example_ja": "八百万の願いが集まる。"},
    "剥離": {"reading_hiragana": "はくり", "zh_gloss_short": "剝離、脫離", "example_ja": "塗装の剥離が進んでいる。"},
    "単純": {"reading_hiragana": "たんじゅん", "zh_gloss_short": "單純", "example_ja": "理由は単純だった。"},
    "取り戻す": {"reading_hiragana": "とりもどす", "zh_gloss_short": "取回、恢復", "example_ja": "自信を取り戻したい。"},
    "古今未曾有": {"reading_hiragana": "ここんみぞう", "zh_gloss_short": "空前絕後", "example_ja": "古今未曾有の出来事だった。"},
    "叱責": {"reading_hiragana": "しっせき", "zh_gloss_short": "斥責、責罵", "example_ja": "彼は上司に叱責された。"},
    "号哭": {"reading_hiragana": "ごうこく", "zh_gloss_short": "號哭、痛哭", "example_ja": "彼女はその場で号哭した。"},
    "名も無い": {"reading_hiragana": "なもない", "zh_gloss_short": "無名的", "example_ja": "名も無い花が咲いていた。"},
    "吐瀉物": {"reading_hiragana": "としゃぶつ", "zh_gloss_short": "嘔吐物", "example_ja": "床に吐瀉物が落ちていた。"},
    "呪う": {"reading_hiragana": "のろう", "zh_gloss_short": "詛咒", "example_ja": "過去を呪っても戻らない。"},
    "咽返る": {"reading_hiragana": "むせかえる", "zh_gloss_short": "嗆得喘不過氣", "example_ja": "煙で咽返るようだった。"},
    "哨戒": {"reading_hiragana": "しょうかい", "zh_gloss_short": "巡邏、警戒", "example_ja": "夜の海を哨戒する。"},
    "嗤う": {"reading_hiragana": "わらう", "zh_gloss_short": "譏笑、嗤笑", "example_ja": "他人を嗤うのはよくない。"},
    "因果応報": {"reading_hiragana": "いんがおうほう", "zh_gloss_short": "善惡有報", "example_ja": "因果応報だと思った。"},
    "埋める": {"reading_hiragana": "うめる", "zh_gloss_short": "填補、埋起來", "example_ja": "差を埋める努力をした。"},
    "声を枯らす": {"reading_hiragana": "こえをからす", "zh_gloss_short": "喊到沙啞", "example_ja": "声を枯らして応援した。"},
    "大往生": {"reading_hiragana": "だいおうじょう", "zh_gloss_short": "善終", "example_ja": "祖父は大往生だった。"},
    "大胆不敵": {"reading_hiragana": "だいたんふてき", "zh_gloss_short": "大膽無畏", "example_ja": "大胆不敵な作戦に出た。"},
    "宛にならない（当てにならない）": {"reading_hiragana": "あてにならない", "zh_gloss_short": "靠不住", "example_ja": "そのうわさは宛にならない。"},
    "届かない": {"reading_hiragana": "とどかない", "zh_gloss_short": "傳達不到", "example_ja": "思いが相手に届かない。"},
    "届けたい": {"reading_hiragana": "とどけたい", "zh_gloss_short": "想傳達出去", "example_ja": "この声を君に届けたい。"},
    "幽閉": {"reading_hiragana": "ゆうへい", "zh_gloss_short": "幽禁、關起來", "example_ja": "塔に幽閉された姫のようだ。"},
    "強がり": {"reading_hiragana": "つよがり", "zh_gloss_short": "逞強", "example_ja": "彼女は強がりをやめた。"},
    "後悔": {"reading_hiragana": "こうかい", "zh_gloss_short": "後悔", "example_ja": "今さら後悔しても遅い。"},
    "得意げ": {"reading_hiragana": "とくいげ", "zh_gloss_short": "得意洋洋的", "example_ja": "彼は得意げに話した。"},
    "急速に": {"reading_hiragana": "きゅうそくに", "zh_gloss_short": "迅速地", "example_ja": "温度が急速に下がった。"},
    "恐る恐る": {"reading_hiragana": "おそるおそる", "zh_gloss_short": "戰戰兢兢地", "example_ja": "恐る恐る扉を開けた。"},
    "息を潜める": {"reading_hiragana": "いきをひそめる", "zh_gloss_short": "屏住呼吸", "example_ja": "みんな息を潜めて待った。"},
    "惰眠を謳歌する": {"reading_hiragana": "だみんをおうかする", "zh_gloss_short": "沉迷睡懶覺", "example_ja": "休日に惰眠を謳歌した。"},
    "惹かれあう": {"reading_hiragana": "ひかれあう", "zh_gloss_short": "彼此吸引", "example_ja": "二人は自然に惹かれあう。"},
    "推し量らない": {"reading_hiragana": "おしはからない", "zh_gloss_short": "不去揣測", "example_ja": "他人の痛みは簡単に推し量らない。"},
    "操る": {"reading_hiragana": "あやつる", "zh_gloss_short": "操縱、支配", "example_ja": "指先で糸を操る。"},
    "断頭台": {"reading_hiragana": "だんとうだい", "zh_gloss_short": "斷頭台", "example_ja": "断頭台のような緊張が走った。"},
    "日常茶飯事": {"reading_hiragana": "にちじょうさはんじ", "zh_gloss_short": "家常便飯", "example_ja": "寝不足は日常茶飯事だ。"},
    "最低最悪": {"reading_hiragana": "さいていさいあく", "zh_gloss_short": "糟到極點", "example_ja": "今日は最低最悪の気分だ。"},
    "最早": {"reading_hiragana": "もはや", "zh_gloss_short": "已經、如今", "example_ja": "最早迷いはなかった。"},
    "望む": {"reading_hiragana": "のぞむ", "zh_gloss_short": "期望、希望", "example_ja": "平和な明日を望む。"},
    "棒に振った": {"reading_hiragana": "ぼうにふった", "zh_gloss_short": "白白斷送", "example_ja": "努力を棒に振った。"},
    "浪費": {"reading_hiragana": "ろうひ", "zh_gloss_short": "浪費", "example_ja": "時間を浪費したくない。"},
    "演じる": {"reading_hiragana": "えんじる", "zh_gloss_short": "扮演、演出", "example_ja": "彼は悪役を演じる。"},
    "潔癖": {"reading_hiragana": "けっぺき", "zh_gloss_short": "潔癖", "example_ja": "彼は少し潔癖だ。"},
    "潰れる": {"reading_hiragana": "つぶれる", "zh_gloss_short": "垮掉、倒閉", "example_ja": "小さな店が潰れた。"},
    "炎天下": {"reading_hiragana": "えんてんか", "zh_gloss_short": "烈日之下", "example_ja": "炎天下で走り続けた。"},
    "無垢": {"reading_hiragana": "むく", "zh_gloss_short": "純真無垢", "example_ja": "無垢な笑顔がまぶしい。"},
    "煩わしい": {"reading_hiragana": "わずらわしい", "zh_gloss_short": "麻煩、煩人", "example_ja": "煩わしい手続きが多い。"},
    "猥雑": {"reading_hiragana": "わいざつ", "zh_gloss_short": "雜亂庸俗", "example_ja": "猥雑な通りを歩いた。"},
    "現実逃避": {"reading_hiragana": "げんじつとうひ", "zh_gloss_short": "逃避現實", "example_ja": "ゲームで現実逃避した。"},
    "理不尽": {"reading_hiragana": "りふじん", "zh_gloss_short": "不講理", "example_ja": "理不尽な要求に困った。"},
    "甲高い": {"reading_hiragana": "かんだかい", "zh_gloss_short": "尖銳高亢", "example_ja": "甲高い声が響いた。"},
    "百戦錬磨": {"reading_hiragana": "ひゃくせんれんま", "zh_gloss_short": "身經百戰", "example_ja": "彼は百戦錬磨の営業だ。"},
    "真っ先に": {"reading_hiragana": "まっさきに", "zh_gloss_short": "最先、率先", "example_ja": "彼は真っ先に手を挙げた。"},
    "真逆": {"reading_hiragana": "まぎゃく", "zh_gloss_short": "完全相反", "example_ja": "答えは予想と真逆だった。"},
    "確かに": {"reading_hiragana": "たしかに", "zh_gloss_short": "的確地、確實", "example_ja": "彼の言うことは確かに正しい。"},
    "空く": {"reading_hiragana": "すく", "zh_gloss_short": "空出、變空", "example_ja": "前の席が空いた。"},
    "範疇": {"reading_hiragana": "はんちゅう", "zh_gloss_short": "範圍、類別", "example_ja": "これは私の範疇ではありません。"},
    "糜爛": {"reading_hiragana": "びらん", "zh_gloss_short": "潰爛、糜爛", "example_ja": "傷口が糜爛していた。"},
    "継ぎ接ぎ": {"reading_hiragana": "つぎはぎ", "zh_gloss_short": "拼湊、縫補", "example_ja": "継ぎ接ぎだらけの話だった。"},
    "縋れ": {"reading_hiragana": "すがれ", "zh_gloss_short": "抓住、依靠吧", "example_ja": "最後の希望に縋れ。"},
    "臨終": {"reading_hiragana": "りんじゅう", "zh_gloss_short": "臨終", "example_ja": "家族が臨終に立ち会った。"},
    "自己嫌悪": {"reading_hiragana": "じこけんお", "zh_gloss_short": "自我厭惡", "example_ja": "失敗して自己嫌悪に陥った。"},
    "蛇蝎": {"reading_hiragana": "だかつ", "zh_gloss_short": "像蛇蠍般可憎", "example_ja": "彼は蛇蝎のごとく嫌われた。"},
    "見る影もない": {"reading_hiragana": "みるかげもない", "zh_gloss_short": "完全不復從前", "example_ja": "昔の町は見る影もない。"},
    "論より証拠": {"reading_hiragana": "ろんよりしょうこ", "zh_gloss_short": "事實勝於雄辯", "example_ja": "論より証拠だ。見てほしい。"},
    "論外": {"reading_hiragana": "ろんがい", "zh_gloss_short": "不值一提、離譜", "example_ja": "その案は論外だ。"},
    "諦め": {"reading_hiragana": "あきらめ", "zh_gloss_short": "放棄、死心", "example_ja": "諦めはまだ早い。"},
    "諸行無常": {"reading_hiragana": "しょぎょうむじょう", "zh_gloss_short": "世事無常", "example_ja": "諸行無常を感じた。"},
    "賞味期限": {"reading_hiragana": "しょうみきげん", "zh_gloss_short": "賞味期限", "example_ja": "牛乳の賞味期限を見た。"},
    "踠いたって": {"reading_hiragana": "もがいたって", "zh_gloss_short": "再怎麼掙扎也", "example_ja": "踠いたって答えは出ない。"},
    "退屈": {"reading_hiragana": "たいくつ", "zh_gloss_short": "無聊", "example_ja": "長い会議は退屈だった。"},
    "退廃": {"reading_hiragana": "たいはい", "zh_gloss_short": "頹廢", "example_ja": "退廃した空気が漂う。"},
    "郷愁": {"reading_hiragana": "きょうしゅう", "zh_gloss_short": "鄉愁", "example_ja": "古い景色に郷愁を覚えた。"},
    "醜態": {"reading_hiragana": "しゅうたい", "zh_gloss_short": "醜態、出糗", "example_ja": "人前で醜態をさらした。"},
    "金輪際": {"reading_hiragana": "こんりんざい", "zh_gloss_short": "今後絕不", "example_ja": "金輪際うそはつかない。"},
    "間違ったまま": {"reading_hiragana": "まちがったまま", "zh_gloss_short": "一直錯下去", "example_ja": "間違ったまま進みたくない。"},
    "頼りない": {"reading_hiragana": "たよりない", "zh_gloss_short": "不可靠", "example_ja": "彼の返事は頼りない。"},
    "駆け足": {"reading_hiragana": "かけあし", "zh_gloss_short": "快步、小跑", "example_ja": "駅まで駆け足で向かった。"},
    "驚天動地": {"reading_hiragana": "きょうてんどうち", "zh_gloss_short": "驚天動地", "example_ja": "驚天動地の知らせが届いた。"},
    "魁星": {"reading_hiragana": "かいせい", "zh_gloss_short": "先驅之星", "example_ja": "夜空に魁星が光った。"},
    "魅了": {"reading_hiragana": "みりょう", "zh_gloss_short": "魅惑、吸引", "example_ja": "その声の魅了は強い。"},
    "魅了する": {"reading_hiragana": "みりょうする", "zh_gloss_short": "使著迷", "example_ja": "音だけで人を魅了する。"},
}
